version: '3.8'


networks:
  viixoo-hemago_mrp:
    external: True

services:
  backend:
    container_name: viixoo_hemago_backend
    build: 
      context: ./viixoo_core
      dockerfile: ./docker/dev.DockerFile
    command:
      [
        "sh",
        "-c",
        "pip install --upgrade debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:5679 --wait-for-client -m uvicorn viixoo_core.viixoo_core.app:app --host 0.0.0.0 --reload --port 8002",
      ]
    ports:
      - "8000:8000"
    volumes:
      - ./viixoo_core:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    env_file:
      - ./viixoo_core/docker/service.env

  frontend:
    container_name: viixoo_hemago_frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./viixoo_frontend_apps/docker/service.env
    build:
      context: ./viixoo_frontend_apps
      dockerfile: ./docker/dev.DockerFile
      args:
        - VITE_API_URL=${VITE_API_URL:-https://api.default.com}
        - NODE_ENV=production

