version: '3.8'


networks:
  viixoo-hemago-mrp:
    external: True

services:
  backend_dev:
    container_name: viixoo_hemago_backend_dev
    build: 
      context: ./viixoo_core
      dockerfile: ./docker/dev.DockerFile
    command:
      [
        "sh",
        "-c",
        "pip install --upgrade debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:5679 --wait-for-client -m uvicorn viixoo_core.viixoo_core.app:app --host 0.0.0.0 --reload --port 8002",
      ]
    ports:
      - "8002:8002"
    volumes:
      - ./viixoo_core:/app
    healthcheck:
       test: ["CMD", "curl", "-f", "http://localhost:8002/api/v1/utils/health-check/"]
       interval: 10s
       timeout: 5s
       retries: 5
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    env_file:
      - ./viixoo_core/docker/service.env

  backend_prod:
    container_name: viixoo_hemago_backend_prod
    build: 
      context: ./viixoo_core
      dockerfile: ./docker/prod.DockerFile
    command: ["uvicorn", "viixoo_core.viixoo_core.app:app", "--host", "0.0.0.0", "--reload", "--port", "8000"]
    ports:
      - "8000:8000"
    volumes:
      - ./viixoo_core:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    env_file:
      - ./viixoo_core/docker/service.env

  frontend:
    container_name: viixoo_hemago_frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ./viixoo_frontend_apps/docker/service.env
    build:
      context: ./viixoo_frontend_apps
      dockerfile: ./docker/dev.DockerFile
      args:
        - VITE_API_URL=${VITE_API_URL:-https://api.default.com}
        - NODE_ENV=production

