name: IaC Deploy

on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.2

      - name: Terraform Init
        working-directory: viixoo_app_engine/IaC/terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: viixoo_app_engine/IaC/terraform
        run: terraform plan

      - name: Terraform Apply
        working-directory: viixoo_app_engine/IaC/terraform
        run: |
          terraform apply -auto-approve
          echo "::set-output name=instance_id::$(terraform output instance_id)"
          echo "instance_id=$(terraform output -raw instance_id)" >> $GITHUB_OUTPUT
          echo "public_ip=$(terraform output -raw instance_public_ip)" >> $GITHUB_OUTPUT
